In [ ]:
import numpy as np

In [ ]:
n_neurons=50
neurons=np.random.uniform(0, 180, n_neurons)




In [ ]:
neurons

array([ 66.23882264,  61.85722215,   3.18135924, 131.657559  ,
       114.26238771,  75.21007359, 171.80341336, 100.8849853 ,
       169.21774216, 163.14791345, 155.3724054 ,  56.65462482,
        84.69933813, 151.50540661,  66.98777314,  95.68472326,
        36.8338969 ,  47.06884069,  66.34695284, 141.75310074,
       103.58581664, 104.44946712,  95.56642756,  55.13960067,
        18.85842806,  35.3491647 ,  62.31653363,  89.59209987,
        37.95049226,  67.59610882, 166.01627916,  17.09759374,
       162.51377471,  27.23183601, 107.18204053, 168.53436721,
        78.43354214,  59.54657001,  81.863902  , 117.21263433,
        25.30803517, 155.43045717,  68.0200039 ,  53.57447304,
        27.3254847 ,  58.20844383, 144.85374889,  81.23152648,
        73.95026169, 166.4925103 ])

In [ ]:
def strengh(stimulus, prefered, r_max=100):
    dif = abs(stimulus - prefered)
    dif = np.minimum(dif, 180 - dif)
    dif = np.radians(dif)
    response = r_max*np.cos(dif)
    return max(0, response)

In [ ]:
stimulus = [0, 22.5, 45, 67.5, 90, 112.5, 135, 157.5]

result = np.zeros((n_neurons, len(stimulus), 30))

for i in range(n_neurons):
    for j in range(len(stimulus)):
        for k in range(30):
            result[i, j, k] = np.random.poisson(strengh(stimulus[j], neurons[i]))


In [ ]:
result


array([[[ 30.,  32.,  46., ...,  32.,  66.,  39.],
        [ 81.,  76.,  80., ...,  90.,  86.,  71.],
        [ 76.,  81., 107., ...,  71.,  85.,  86.],
        ...,
        [ 66.,  72.,  72., ...,  76.,  73.,  81.],
        [ 42.,  32.,  35., ...,  35.,  31.,  27.],
        [  1.,   2.,   2., ...,   1.,   3.,   1.]],

       [[ 39.,  54.,  40., ...,  58.,  47.,  48.],
        [ 73.,  72.,  64., ...,  76.,  79.,  78.],
        [102., 122.,  97., ...,  85.,  97., 114.],
        ...,
        [ 54.,  61.,  62., ...,  70.,  68.,  84.],
        [ 28.,  26.,  23., ...,  32.,  34.,  31.],
        [  5.,   8.,  10., ...,  10.,   8.,   7.]],

       [[104.,  98.,  78., ..., 105., 109.,  89.],
        [ 81.,  82.,  95., ..., 104., 107.,  93.],
        [ 77.,  85.,  77., ...,  78.,  74.,  65.],
        ...,
        [ 28.,  34.,  37., ...,  35.,  37.,  33.],
        [ 74.,  69.,  82., ...,  80.,  71.,  68.],
        [ 81.,  89.,  90., ...,  99.,  85.,  99.]],

       ...,

       [[ 14.,  18.,  15

In [ ]:
np.savez_compressed('result.npz', result=result)

data = np.load("result.npz")
result_loaded = data["result"]
result_loaded



array([[[ 30.,  32.,  46., ...,  32.,  66.,  39.],
        [ 81.,  76.,  80., ...,  90.,  86.,  71.],
        [ 76.,  81., 107., ...,  71.,  85.,  86.],
        ...,
        [ 66.,  72.,  72., ...,  76.,  73.,  81.],
        [ 42.,  32.,  35., ...,  35.,  31.,  27.],
        [  1.,   2.,   2., ...,   1.,   3.,   1.]],

       [[ 39.,  54.,  40., ...,  58.,  47.,  48.],
        [ 73.,  72.,  64., ...,  76.,  79.,  78.],
        [102., 122.,  97., ...,  85.,  97., 114.],
        ...,
        [ 54.,  61.,  62., ...,  70.,  68.,  84.],
        [ 28.,  26.,  23., ...,  32.,  34.,  31.],
        [  5.,   8.,  10., ...,  10.,   8.,   7.]],

       [[104.,  98.,  78., ..., 105., 109.,  89.],
        [ 81.,  82.,  95., ..., 104., 107.,  93.],
        [ 77.,  85.,  77., ...,  78.,  74.,  65.],
        ...,
        [ 28.,  34.,  37., ...,  35.,  37.,  33.],
        [ 74.,  69.,  82., ...,  80.,  71.,  68.],
        [ 81.,  89.,  90., ...,  99.,  85.,  99.]],

       ...,

       [[ 14.,  18.,  15

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7a0e9b48-d539-4b72-9571-cc0e76c4f674' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>