## Task 1. Neural Population Coding
Petra Reuwsaat Paul

Background
You are analyzing neural recordings from a population of 50 neurons in visual cortex. Each neuron has a preferred orientation (the visual angle it responds to most strongly). Your goal is to understand how a group of these neurons works together in the presence of noise.
1: Generate a Synthetic Neural Population
Create a population of 50 neurons where each neuron has a randomly assigned preferred orientation between 0° and 180°. [hint: use np.random.uniform()]

In [8]:
import numpy as np

In [9]:
n_neurons=50
neurons=np.random.uniform(0, 180, n_neurons)




In [10]:
neurons

array([144.48688526,  68.85066601,  31.64302687,  49.1340769 ,
        15.79452487,  80.55555216, 106.37614023, 108.10366461,
        87.84030198, 155.41681441, 131.69340842, 145.43906249,
       139.8086879 , 148.12054103, 142.39511279, 179.53317067,
       174.01655953, 150.61400272, 161.36722638,   5.99245875,
       122.04962576, 123.12009282,  70.69377516,  77.28292687,
       123.31221367,  32.26971081,  55.39439178, 139.88564993,
        72.47741409, 150.17769393, 173.16362298,  49.40621994,
        54.15641212, 173.43933737, 175.69887561, 160.95650519,
       115.64540494, 122.91069715,  36.817715  ,  24.47038423,
         1.98532832,  90.26370235,  31.04399158,  68.53117563,
        84.08777075,  43.61641626, 132.13207415,  88.47609989,
        49.74065142, 109.70309246])

## 2: Simulate Neural Responses
Check the neurons responses to 8 different stimulus orientations: 0°, 22.5°, 45°, 67.5°, 90°, 112.5°, 135°, and 157.5°. write a function to calculate neurons response.

Write a function that calculates how strongly a neuron fires:
• Inputs: stimulus orientation, neuron’s preferred orientation and maximum firing rate (r_max = 100 spikes/second)
• Output: the firing rate (response)
• Your function should:
• Calculate the difference between the stimulus angle and the neuron's preferred angle
• Remember: orientations are circular! 0° and 180° are similar, remember to handle wraparound [hint: use np.minimum(diff, 180 - diff)]
• Use cosine tuning: response = r_max * cos(difference in radians)
• Make sure responses are not negative

In [4]:
def strengh(stimulus, prefered, r_max=100):
    dif = abs(stimulus - prefered)
    dif = np.minimum(dif, 180 - dif)
    dif = np.radians(dif)
    response = r_max*np.cos(dif)
    return max(0, response)

## 3. Generate response data
Simulate responses to 8 stimulus orientations: 0°, 22.5°, 45°, 67.5°, 90°, 112.5°, 135°, and 157.5°. 
For each combination of neuron and stimulus:
• Calculate the response
• Generate 30 trials with Poisson noise(*)
• Store the results in a 3D array with shape (n_neurons, n_stimuli, n_trials)
• Save results to file, we will use it in the next task 😊

(*) Why Poisson noise? Real neurons don't fire exactly the same number of spikes every time - there's randomness. Poisson noise captures this biological variability.

In [5]:
stimulus = [0, 22.5, 45, 67.5, 90, 112.5, 135, 157.5]

result = np.zeros((n_neurons, len(stimulus), 30))

for i in range(n_neurons):
    for j in range(len(stimulus)):
        for k in range(30):
            result[i, j, k] = np.random.poisson(strengh(stimulus[j], neurons[i]))


In [6]:
result


array([[[ 88.,  80.,  82., ...,  74.,  61.,  76.],
        [100., 103.,  98., ...,  72., 101.,  92.],
        [ 99., 104., 125., ..., 104.,  79., 104.],
        ...,
        [ 42.,  31.,  47., ...,  27.,  30.,  33.],
        [  0.,   1.,   1., ...,   4.,   0.,   1.],
        [ 41.,  42.,  36., ...,  48.,  50.,  38.]],

       [[ 55.,  60.,  56., ...,  76.,  47.,  49.],
        [ 86.,  84.,  84., ...,  76.,  81.,  77.],
        [ 99.,  91.,  93., ..., 105., 101.,  88.],
        ...,
        [ 44.,  45.,  54., ...,  56.,  55.,  49.],
        [ 18.,  18.,  10., ...,  15.,  21.,  19.],
        [ 18.,  23.,  22., ...,  27.,  28.,  23.]],

       [[ 34.,  25.,  28., ...,  27.,  25.,  30.],
        [ 58.,  63.,  66., ...,  59.,  61.,  58.],
        [ 91.,  93.,  84., ...,  86., 102.,  76.],
        ...,
        [ 65.,  86.,  74., ...,  86.,  84.,  87.],
        [ 51.,  53.,  36., ...,  53.,  42.,  48.],
        [  9.,   5.,  12., ...,  10.,  14.,  10.]],

       ...,

       [[ 79.,  64.,  77

In [12]:
np.savez_compressed('result.npz', 
                    result=result,
                    neurons=neurons,
                    stimulus=stimulus)

data = np.load("result.npz")
result_loaded = data["result"]
result_loaded



array([[[ 88.,  80.,  82., ...,  74.,  61.,  76.],
        [100., 103.,  98., ...,  72., 101.,  92.],
        [ 99., 104., 125., ..., 104.,  79., 104.],
        ...,
        [ 42.,  31.,  47., ...,  27.,  30.,  33.],
        [  0.,   1.,   1., ...,   4.,   0.,   1.],
        [ 41.,  42.,  36., ...,  48.,  50.,  38.]],

       [[ 55.,  60.,  56., ...,  76.,  47.,  49.],
        [ 86.,  84.,  84., ...,  76.,  81.,  77.],
        [ 99.,  91.,  93., ..., 105., 101.,  88.],
        ...,
        [ 44.,  45.,  54., ...,  56.,  55.,  49.],
        [ 18.,  18.,  10., ...,  15.,  21.,  19.],
        [ 18.,  23.,  22., ...,  27.,  28.,  23.]],

       [[ 34.,  25.,  28., ...,  27.,  25.,  30.],
        [ 58.,  63.,  66., ...,  59.,  61.,  58.],
        [ 91.,  93.,  84., ...,  86., 102.,  76.],
        ...,
        [ 65.,  86.,  74., ...,  86.,  84.,  87.],
        [ 51.,  53.,  36., ...,  53.,  42.,  48.],
        [  9.,   5.,  12., ...,  10.,  14.,  10.]],

       ...,

       [[ 79.,  64.,  77

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7a0e9b48-d539-4b72-9571-cc0e76c4f674' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>